#!/bin/bash
verifyItWorkes()
{
    for profile in "${profiles[@]}"; do
        if [ -f """$profile""" ]; then
            break
        fi
    done
    unset MOOSE_JOBS
    source """$profile"""
    if [ -z "$MOOSE_JOBS" ]; then
        error_message="""Installer script wrote changes to\n\n\t$use_this_profile\n\nbut was unable to determine the presence of key MOOSE-environment vairables in a new terminal session. While not infallible, this installer believes your environment is not working properly."""
        response=`osascript -e 'display alert "'"$error_message"'"' 2>/dev/null`
    else
        explainNewTerminal
    fi
}

function findCorrectProfile()
{
    # Loop through each found profile and determine the last profile being sourced
    reverse_priority_array=()
    for profile in "${profiles[@]}"; do
        if [ -f """$profile""" ] && ! [ -L """$profile""" ]; then reverse_priority_array=("""$profile""" """${reverse_priority_array[@]}"""); fi
    done

    # No profile exists
    if [ "${reverse_priority_array}x" = "x" ]; then
        reverse_priority_array=("""${profiles[${#profiles[@]}-1]}""")
    fi

    for found_profile in "${reverse_priority_array[@]}"; do
        if [ -n "$previous_priority_profile" ]; then
            if [ `grep -c \\\\$(basename """$previous_priority_profile""") """$found_profile"""` -ge 1 ]; then
                use_this_profile="""$previous_priority_profile"""
            else
                use_this_profile="""$found_profile"""
            fi
        fi
        previous_priority_profile=$found_profile
    done
    use_this_profile=${use_this_profile:-"""$found_profile"""}
}

function detectAndCreateProfile()
{
    if [ -z "$use_this_profile" ]; then
        findCorrectProfile
    fi

    # Fix previous versions of the bash_profile (add header/footer to our sourcing profile to make it easier to remove/alter)
    if [ `grep -c "#MOOSE_ENVIRONMENT" """$use_this_profile"""` -eq 0 ]; then
      sed -i '' -e $'s/# Uncomment to enable pretty prompt:/#MOOSE_ENVIRONMENT\\\n# Uncomment to enable pretty prompt:/g' """$use_this_profile"""
      sed -i '' -e $'/environments\/moose_profile$/{n;s/^fi/fi\\\n#ENDMOOSE_ENVIRONMENT/;}' """$use_this_profile"""
    fi

    # Remove source section, so we can add changes
    sed -i '' -e '/#MOOSE_ENVIRONMENT/,/#ENDMOOSE_ENVIRONMENT/d' """$use_this_profile"""

    cat >> """$use_this_profile""" << EOF
#MOOSE_ENVIRONMENT
# Uncomment to enable autojump:
# export MOOSE_JUMP=true

# Source MOOSE profile
if [ -f <PACKAGES_DIR>/environments/moose_profile ]; then
        . <PACKAGES_DIR>/environments/moose_profile

        # Make the moose compiler stack available.
        # Note: if you have any additional package managers installed
        # (Homebrew, Macports, Fink, etc) know that you must perform
        # the following command _after_ the source commands for the
        # afore mentioned package managers.
        module load moose-dev-clang
fi
#ENDMOOSE_ENVIRONMENT
EOF
    chown """$USER:staff""" """$use_this_profile"""
}

function explainProfile()
{
    message="""You have selected not to setup the MOOSE environment. If you choose cancel here, know that nothing will work, until you source the moose_profile script on your own. By selecting OK, the following will be appended to your\n\n\t$use_this_profile\n\n# Uncomment to enable pretty prompt:\n# export 'MOOSE_PROMPT=true\n\n# Uncomment to enable autojump:\n# export MOOSE_JUMP=true\n\n# Source MOOSE profile\nif [ -f <PACKAGES_DIR>/environments/moose_profile ]; then\n\t. <PACKAGES_DIR>/environments/moose_profile\nfi"""
    response=`osascript -e 'tell app "System Events" to display dialog "'"$message"'"' 2>/dev/null`

    if [ "$response" == "button returned:OK" ]; then
        detectAndCreateProfile
        verifyItWorkes
    fi
}
function explainNewTerminal()
{
    message="""Your bash profile has been updated.\n\nRemember to close any opened terminal windows and re-open them to gain access to the moose-environment you just installed."""
    response=`osascript -e 'display alert "'"$message"'"' 2>/dev/null`
}

profiles=("""$HOME/.zshrc""" """$HOME/.bash_profile""")

findCorrectProfile
if ! [ -f """$use_this_profile""" ]; then
    explainProfile
elif [ `grep -c environments/moose_profile """$use_this_profile"""` -le 0 ]; then
    explainProfile
fi
