#!/bin/bash
#############
## Specifics
##
DEP=(modules)
PACKAGE='autoconf'

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.org/source_packages/<AUTOCONF>.tar.gz'
EXTRACT='<AUTOCONF>.tar.gz'
CONFIGURE="./configure --prefix=$PACKAGES_DIR/autotools"
BUILD='true'
INSTALL='true'

pre_run() {
    return
}

post_run() {
    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/adv_modules/autotools
#%Module1.0#####################################################################
##
## Autotools Module file
##
##
##
set BASE_PATH       $PACKAGES_DIR
prepend-path        PATH       \$BASE_PATH/autotools/bin
EOF
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
