#!/bin/bash
#############
## Specifics
##
DEP=(moose_profile)
PACKAGE='autojump'
SERIAL=True

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='false'
EXTRACT='false'
CONFIGURE="false"
BUILD='false'
INSTALL='false'

pre_run() {
    if [ -d $PACKAGES_DIR/autojump ]; then
      rm -rf $PACKAGES_DIR/autojump
    fi
    cd $1
    try_command 3 "git clone https://github.com/joelthelion/autojump.git"
    cd autojump
    if [ $? -ne 0 ]; then echo 'Failed to clone autojump repo'; cleanup 1; fi
    git checkout fd287eab041f1677320a2f7a5e94bb601c2e706e
    ./install.sh --local  --bash --prefix $PACKAGES_DIR/autojump
}
post_run() {
    cat <<EOF > $PACKAGES_DIR/environments/autojump_profile
export PATH=$PACKAGES_DIR/autojump/bin:\$PATH
export MANPATH=$PACKAGES_DIR/autojump/share/man:\$MANPATH
source $PACKAGES_DIR/autojump/etc/profile.d/autojump.bash
EOF
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup 0|1  (exit return code)

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
