#!/bin/bash
#############
## Specifics
##
DEP=(moose_profile)
PACKAGE='autocomplete'

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='false'
EXTRACT='false'
CONFIGURE="false"
BUILD='false'
INSTALL='false'

pre_run() {
    return
}
post_run() {
    cp "$RELATIVE_DIR/autocomplete_moose" "$PACKAGES_DIR/environments/autocomplete_moose"
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup 0|1  (exit return code)

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
