#!/bin/bash
#############
## Specifics
##
DEP=(modules miniconda)

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='false'
EXTRACT='false'
CONFIGURE='false'
BUILD='false'
INSTALL='false'

pre_run() {
    unset MODULEPATH
    source "$PACKAGES_DIR/Modules/init/bash"
    module load miniconda
    try_command 5 "PATH=$PACKAGES_DIR/miniconda/bin:$PATH conda install boost gmp mpfr --yes"
}

post_run() {
    cat <<EOF > "$PACKAGES_DIR/Modules/<MODULES>/adv_modules/boost"
#%Module1.0#####################################################################
##
## boost Module file
##
##
##
set BASE_PATH       "$PACKAGES_DIR"
prepend-path        PATH       "\$BASE_PATH/miniconda/bin"
setenv              BOOST_DIR  "\$BASE_PATH/miniconda"
EOF
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR="<PACKAGES_DIR>"
RELATIVE_DIR="<RELATIVE_DIR>"
DOWNLOAD_DIR="<DOWNLOAD_DIR>"
TEMP_PREFIX="<TEMP_PREFIX>"
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
DOWNLOAD_ONLY=<DOWNLOAD_ONLY>
source "$RELATIVE_DIR/functions" $@
