#!/bin/bash
#############
## Specifics
##
DEP=(modules)
PACKAGE="<CCACHE>"

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.org/source_packages/<CCACHE>.tar.gz'
EXTRACT='<CCACHE>.tar.gz'
CONFIGURE="true"
BUILD='true'
INSTALL='true'

pre_run() {
    return
}
post_run() {
    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/modulefiles/ccache
#%Module1.0#####################################################################
##
## <CCACHE> modulefile
##
##
##
set              BASE_PATH        $PACKAGES_DIR

prepend-path     PATH               \$BASE_PATH/<CCACHE>/bin
prepend-path     MANPATH            \$BASE_PATH/<CCACHE>/share/man

if {[is-loaded moose/.<GCC>] || [is-loaded <GCC>]} {
  setenv           CC                 "ccache gcc"
  setenv           CXX                "ccache g++"
}
if {[is-loaded moose/.<CLANG>] || [is-loaded <CLANG>]} {
  setenv           CC                 "ccache clang"
  setenv           CXX                "ccache clang++"
}

# Civet specific support for Intel compiler
if {[is-loaded moose/.intel] || [is-loaded intel]} {
  setenv           CC                 "ccache icc"
  setenv           CXX                "ccache icpc"
}

setenv           CCACHE_SLOPPINESS  "time_macros" 
EOF
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR=<PACKAGES_DIR>
RELATIVE_DIR=<RELATIVE_DIR>
DOWNLOAD_DIR=<DOWNLOAD_DIR>
TEMP_PREFIX=<TEMP_PREFIX>
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
source $RELATIVE_DIR/functions $@
