#!/bin/bash
#############
## Specifics
##
# DO LAST (or at least when we know we are done installing miniconda modules)
DEP=(miniconda module-moose-dev-gcc module-moose-dev-clang)
PACKAGE='clean-conda'
SERIAL=True

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='false'
EXTRACT='false'
CONFIGURE="false"
BUILD='false'
INSTALL='false'

pre_run() {
    PATH="$PACKAGES_DIR/miniconda/bin:$PATH" conda clean --lock --tarballs --index-cache --packages --source-cache --yes
    rm -rf "$PACKAGES_DIR/miniconda/pkgs/"*
    touch "$PACKAGES_DIR/miniconda/pkgs/urls.txt"
    # Clean up these empty temp directories conda install seems to leave behind
    rm -rf "$PACKAGES_DIR/miniconda/".cph_tmp*
}
post_run() {
    return
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup 0|1  (exit return code)

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR="<PACKAGES_DIR>"
RELATIVE_DIR="<RELATIVE_DIR>"
DOWNLOAD_DIR="<DOWNLOAD_DIR>"
TEMP_PREFIX="<TEMP_PREFIX>"
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
DOWNLOAD_ONLY=<DOWNLOAD_ONLY>
source "$RELATIVE_DIR/functions" $@
