#!/bin/bash
#############
## Specifics
##
DEP=(modules gcc)
PACKAGE="<CMAKE>"

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.inl.gov/source_packages/<CMAKE>.tar.gz'
EXTRACT='<CMAKE>.tar.gz'
CONFIGURE="true"
BUILD='true'
INSTALL='true'

pre_run() {
    if [ -d "$PACKAGES_DIR/$PACKAGE" ]; then rm -rf "$PACKAGES_DIR/$PACKAGE"; fi
    unset MODULEPATH
    source "$PACKAGES_DIR/Modules/<MODULES>/init/bash"
    module load advanced_modules gcc
}

post_run() {
    cat <<EOF > "$PACKAGES_DIR/Modules/<MODULES>/adv_modules/cmake"
#%Module1.0#####################################################################
##
## <CMAKE> modulefile
##
##
##
set          BASE_PATH          "$PACKAGES_DIR"

prepend-path PATH               "\$BASE_PATH/<CMAKE>/bin"
EOF
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR="<PACKAGES_DIR>"
RELATIVE_DIR="<RELATIVE_DIR>"
DOWNLOAD_DIR="<DOWNLOAD_DIR>"
TEMP_PREFIX="<TEMP_PREFIX>"
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
DOWNLOAD_ONLY=<DOWNLOAD_ONLY>
source "$RELATIVE_DIR/functions" $@
