#!/bin/bash
#############
## Specifics
##
DEP=(modules gcc)
PACKAGE="<GCC>"
BASE_DIR="<CPPUNIT>"

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.inl.gov/source_packages/<CPPUNIT>.tar.gz'
EXTRACT='<CPPUNIT>.tar.gz'
CONFIGURE='false'
BUILD='true'
INSTALL='true'

pre_run() {
    unset MODULEPATH
    source "$PACKAGES_DIR/Modules/<MODULES>/init/bash"
    module load moose/.<GCC>
    # we have to run this our selves with out error checking. Mac machines appear to exhibit a bug:
    #
    # rm: conftest.dSYS: is a directory
    #
    # autoconf tries to `rm -f` a directory (which requires an additional -r switch) that appears to only
    # be created on Mac machines. So we run ./configure ourselves, and unfortunately on-purpose _not_
    # check for a failure. If the builds step failes because of 
    if [ `uname` = "Darwin" ]; then
	./configure --prefix="$PACKAGES_DIR/<CPPUNIT>/<GCC>"
    else
        CONFIGURE='true'
    fi
}

post_run() {
    cat <<EOF > "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose/.<CPPUNIT>_<GCC>"
#%Module1.0#####################################################################
##
## <CPPUNIT> <GCC>
##
set          BASE_PATH         "$PACKAGES_DIR"
conflict moose/.<CPPUNIT>_<CLANG> cppunit-clang

set          CPPUNIT_PATH      "\$BASE_PATH/<CPPUNIT>/<GCC>"
setenv       CPPUNIT_DIR       "\$CPPUNIT_PATH"

prepend-path INCLUDE           "\$CPPUNIT_PATH/include"
prepend-path PATH              "\$CPPUNIT_PATH/bin"
EOF
    cd "$PACKAGES_DIR/Modules/<MODULES>/adv_modules"
    if [ -f cppunit-gcc ]; then rm -f cppunit-gcc; fi
    ln -s ../modulefiles/moose/.<CPPUNIT>_<GCC> cppunit-gcc
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR="<PACKAGES_DIR>"
RELATIVE_DIR="<RELATIVE_DIR>"
DOWNLOAD_DIR="<DOWNLOAD_DIR>"
TEMP_PREFIX="<TEMP_PREFIX>"
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
DOWNLOAD_ONLY=<DOWNLOAD_ONLY>
source "$RELATIVE_DIR/functions" $@
