#!/bin/bash
#############
## Specifics
##
DEP=(modules gcc)
PACKAGE='cppunit-gcc'

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.org/source_packages/<CPPUNIT>.tar.gz'
EXTRACT='<CPPUNIT>.tar.gz'
CONFIGURE='false'
BUILD='true'
INSTALL='true'

pre_run() {
    if [ -d $PACKAGES_DIR/<CPPUNIT>/gcc-opt ]; then
	$PACKAGES_DIR/<CPPUNIT>/gcc-opt
    fi
    unset MODULEPATH
    source $PACKAGES_DIR/Modules/<MODULES>/init/bash
    module load advanced_modules gcc
    # we have to run this our selves with out error checking. Mac machines appear to exhibit a bug:
    #
    # rm: conftest.dSYS: is a directory
    #
    # autoconf tries to `rm -f` a directory (which requires an additional -r switch) that appears to only be created on Mac machines.
    if [ `uname` = "Darwin" ]; then
	./configure --prefix=$PACKAGES_DIR/<CPPUNIT>/gcc-opt
    else
	./configure --prefix=$PACKAGES_DIR/<CPPUNIT>/gcc-opt
	if [ $? -ne 0 ]; then echo "Error while configuring cppunit"; cleanup 1; fi
    fi
}

post_run() {
    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose/.<CPPUNIT>-gcc
#%Module1.0#####################################################################
##
## CPPUnit GCC
##
set          BASE_PATH         $PACKAGES_DIR
conflict moose/.cppunit-clang cppunit-clang

set          CPPUNIT_PATH      \$BASE_PATH/<CPPUNIT>/gcc-opt
setenv       CPPUNIT_DIR       \$CPPUNIT_PATH

prepend-path INCLUDE           \$CPPUNIT_PATH/include
prepend-path PATH              \$CPPUNIT_PATH/bin
EOF
    cd $PACKAGES_DIR/Modules/<MODULES>/adv_modules
    ln -s ../modulefiles/moose/.<CPPUNIT>-gcc cppunit-gcc
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
