#!/bin/bash
#############
## Specifics
##
DEP=(modules cmake llvm)
PACKAGE="<DOXYGEN>"

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.inl.gov/source_packages/<DOXYGEN>.src.tar.gz'
EXTRACT='<DOXYGEN>.src.tar.gz'
CONFIGURE='false'
BUILD='true'
INSTALL='true'

pre_run() {
    unset MODULEPATH
    source "$PACKAGES_DIR/Modules/<MODULES>/init/bash"
    module load advanced_modules cmake

    # Apply Mojave patch (Xcode 10 deprecated -mmacosx-version-min=10.5)
    # (should probably just do this for all Darwin targets)
    if [ `uname` = 'Darwin' ] && [ `uname -r | cut -d. -f 1` = '18' ]; then
        module load clang
        export CC=clang CXX=clang++
        cat << EOF > mojave.patch
--- a/CMakeLists.txt    2017-12-25 09:26:10.000000000 -0700
+++ b/CMakeLists.txt    2018-09-26 07:18:18.000000000 -0600
@@ -36,7 +36,7 @@
        set(sqlite3  "1" CACHE INTERNAL "used in settings.h")
 endif()
 
-set(MACOS_VERSION_MIN 10.5)
+set(MACOS_VERSION_MIN 10.6)
 if (use_libclang)
        set(clang    "1" CACHE INTERNAL "used in settings.h")
         find_package(LLVM CONFIG REQUIRED)
EOF
        patch -p1 < mojave.patch
    fi

    mkdir build; cd build
    CONFIGURE="cmake -DCMAKE_INSTALL_PREFIX=$PACKAGES_DIR/<DOXYGEN> -Wno-dev .."
}
post_run() {
    # Remove previous module section
    sed -i'' -e '/#DOXYGEN/,/#ENDDOXYGEN/d' "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-tools"
    # Append new paths to moose-tools module
    cat <<EOF >> "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-tools"
#DOXYGEN
prepend-path    PATH            "\$BASE_PATH/<DOXYGEN>/bin"
prepend-path    MANPATH         "\$BASE_PATH/<DOXYGEN>/man"
#ENDDOXYGEN
EOF
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR="<PACKAGES_DIR>"
RELATIVE_DIR="<RELATIVE_DIR>"
DOWNLOAD_DIR="<DOWNLOAD_DIR>"
TEMP_PREFIX="<TEMP_PREFIX>"
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
DOWNLOAD_ONLY=<DOWNLOAD_ONLY>
source "$RELATIVE_DIR/functions" $@
