#!/bin/bash
#############
## Specifics
##
DEP=(modules pkg-config pcre libffi gettext)
PACKAGE="<GLIB>"

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.inl.gov/source_packages/<GLIB>.tar.gz'
EXTRACT='<GLIB>.tar.gz'
CONFIGURE="false"
BUILD='true'
INSTALL='true'

pre_run() {
    unset MODULEPATH
    source "$PACKAGES_DIR/Modules/<MODULES>/init/bash"
    module load moose-tools
    CONFIGURE="PATH=$PACKAGES_DIR/<PCRE>/bin:$PACKAGES_DIR/<GETTEXT>/bin:$PATH LDFLAGS=-L$PACKAGES_DIR/<GETTEXT>/lib CPPFLAGS=-I$PACKAGES_DIR/<GETTEXT>/include ./configure --prefix=$PACKAGES_DIR/<GLIB>"
}

post_run() {
    cp "$PACKAGES_DIR/<GLIB>/lib/pkgconfig/"* "$PKG_CONFIG_PATH/"
    # Remove previous module section
    sed -i'' -e '/#GLIB/,/#ENDGLIB/d' "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-tools"
    # Append new paths to moose-tools module
    cat <<EOF >> "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-tools"
#GLIB
prepend-path    PATH            "\$BASE_PATH/<GLIB>/bin"
#ENDGLIB
EOF
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR="<PACKAGES_DIR>"
RELATIVE_DIR="<RELATIVE_DIR>"
DOWNLOAD_DIR="<DOWNLOAD_DIR>"
TEMP_PREFIX="<TEMP_PREFIX>"
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
DOWNLOAD_ONLY=<DOWNLOAD_ONLY>
source "$RELATIVE_DIR/functions" $@
