#!/bin/bash
#############
## Specifics
##
DEP=(libunwind)
PACKAGE="<GPERFTOOLS>"

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.inl.gov/source_packages/<GPERFTOOLS>.tar.gz'
EXTRACT='<GPERFTOOLS>.tar.gz'
CONFIGURE='false'
BUILD='true'
INSTALL='true'

pre_run() {
    unset MODULEPATH
    source "$PACKAGES_DIR/Modules/<MODULES>/init/bash"
    if [ `uname` = "Darwin" ]; then
        module load advanced_modules autotools clang
    else
        module load advanced_modules autotools gcc
    fi
    CPPFLAGS="-I$PACKAGES_DIR/<LIBUNWIND>/include" CFLAGS="-I$PACKAGES_DIR/<LIBUNWIND>/include" LDFLAGS="-L$PACKAGES_DIR/<LIBUNWIND>/lib" ./configure --prefix="$PACKAGES_DIR/$PACKAGE" --enable-libunwind
}
post_run() {
    cat <<EOF >> "$PACKAGES_DIR/Modules/<MODULES>/adv_modules/gperf-tools"
#%Module1.0#####################################################################
##
## gperf-tools modulefile
##
##
##
set          BASE_PATH         "$PACKAGES_DIR"
prepend-path PATH              "\$BASE_PATH/$PACKAGE/bin"
prepend-path MANPATH           "\$BASE_PATH/$PACKAGE/share/man"

if { [uname sysname] != "Darwin" } {
  prepend-path LD_LIBRARY_PATH "\$BASE_PATH/$PACKAGE/lib"
}

EOF
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR="<PACKAGES_DIR>"
RELATIVE_DIR="<RELATIVE_DIR>"
DOWNLOAD_DIR="<DOWNLOAD_DIR>"
TEMP_PREFIX="<TEMP_PREFIX>"
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
DOWNLOAD_ONLY=<DOWNLOAD_ONLY>
source "$RELATIVE_DIR/functions" $@
