#!/bin/bash
#############
## Specifics
##
DEP=(modules gcc ccache miniconda)
PACKAGE="intel"

#####
# Set the operating system allowed to build this module
#
ARCH=(Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='false'
EXTRACT='false'
CONFIGURE='false'
BUILD='false'
INSTALL='false'

re_evaluate(){
    pause ${FUNCNAME[0]} "Re-Evaluate variables"
    return
}

pre_run() {
    mkdir -p ${PACKAGES_DIR}_intel/modulefiles
    rm -f "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose/.intel"
    unset MODULEPATH
    source "$PACKAGES_DIR/Modules/<MODULES>/init/bash"
    export MODULEPATH="$MODULEPATH:<WITH_INTEL>/modulefiles"
    module load intel
    export INTEL_VERSION=${INTEL_VERSION-`icc --version | grep ICC | perl -pe 's|.* (\d+)\..*|\1|'`}
}

post_run() {
    cat <<EOF > "${PACKAGES_DIR}_intel/modulefiles/moose-dev-intel"
#%Module1.0#####################################################################
##
## <PETSC_DEFAULT>
## ${PACKAGE}-${INTEL_VERSION}
## <MPICH>
##
module load intel
module load <MPICH>_${PACKAGE}-${INTEL_VERSION}
module load <PETSC_DEFAULT>_<MPICH>_${PACKAGE}-${INTEL_VERSION}-opt
module load <CPPUNIT>_${PACKAGE}-${INTEL_VERSION}
module load ccache
module load moose-tools

setenv CC  "ccache icc"
setenv CXX "ccache icpc"

EOF
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR="<PACKAGES_DIR>"
RELATIVE_DIR="<RELATIVE_DIR>"
DOWNLOAD_DIR="<DOWNLOAD_DIR>"
TEMP_PREFIX="<TEMP_PREFIX>"
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
DOWNLOAD_ONLY=<DOWNLOAD_ONLY>
WITH_INTEL=<WITH_INTEL>
source "$RELATIVE_DIR/functions" $@
