#!/bin/bash
#############
## Specifics
##
DEP=(modules gcc ccache miniconda)
PACKAGE="intel"

#####
# Set the operating system allowed to build this module
#
ARCH=(Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='false'
EXTRACT='false'
CONFIGURE='false'
BUILD='false'
INSTALL='false'

pre_run() {
  return
}

post_run() {
    cat <<EOF > "${PACKAGES_DIR}_intel/modulefiles/moose/.intel"
#%Module1.0#####################################################################
##
## ${PACKAGE} wrapper to system ${PACKAGE}-${INTEL_VERSION} version
## (at the time of this discovery)
##
module load intel
EOF

    cat <<EOF > "${PACKAGES_DIR}_intel/modulefiles/moose-dev-intel"
#%Module1.0#####################################################################
##
## <PETSC_DEFAULT>
## ${PACKAGE}-${INTEL_VERSION}
## <MPICH>
##
module load <MPICH>_${PACKAGE}-${INTEL_VERSION}
module load <PETSC_DEFAULT>_<MPICH>_${PACKAGE}-${INTEL_VERSION}-opt
module load <CPPUNIT>_${PACKAGE}-${INTEL_VERSION}
module load ccache
module load moose-tools

EOF
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR="<PACKAGES_DIR>"
RELATIVE_DIR="<RELATIVE_DIR>"
DOWNLOAD_DIR="<DOWNLOAD_DIR>"
TEMP_PREFIX="<TEMP_PREFIX>"
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
DOWNLOAD_ONLY=<DOWNLOAD_ONLY>
WITH_INTEL=<WITH_INTEL>
source "$RELATIVE_DIR/functions" $@
