#!/bin/bash
#############
## Specifics
##
DEP=(modules)
PACKAGE="<LCOV>"
SERIAL=True

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.inl.gov/source_packages/<LCOV>.tar.gz'
EXTRACT='<LCOV>.tar.gz'
CONFIGURE='false'
BUILD='false'
INSTALL='false'

pre_run() {
    return
}
post_run() {
    cd bin
    if [ `uname` = 'Darwin' ]; then
        sed -i '' -e 's/install -p -D/install/g' install.sh
    else
        sed -i'' -e 's/install -p -D/install/g' install.sh
    fi
    mkdir -p "$PACKAGES_DIR/<LCOV>/usr/bin"
    mkdir -p "$PACKAGES_DIR/<LCOV>/etc"
    mkdir -p "$PACKAGES_DIR/<LCOV>/usr/share/man/man1"
    mkdir -p "$PACKAGES_DIR/<LCOV>/usr/share/man/man5"
    cd ../
    PREFIX="$PACKAGES_DIR/<LCOV>" make install
    # Remove previous module section
    if [ `uname` = 'Darwin' ]; then
        sed -i '' -e '/#LCOV/,/#ENDLCOV/d' "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-tools"
    else
        sed -i'' -e '/#LCOV/,/#ENDLCOV/d' "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-tools"
    fi
    # Append new paths to moose-tools module
    cat <<EOF >> "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-tools"
#LCOV
prepend-path    PATH            "\$BASE_PATH/<LCOV>/usr/bin"
prepend-path    MANPATH         "\$BASE_PATH/<LCOV>/usr/share/man"
#ENDLCOV
EOF
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR="<PACKAGES_DIR>"
RELATIVE_DIR="<RELATIVE_DIR>"
DOWNLOAD_DIR="<DOWNLOAD_DIR>"
TEMP_PREFIX="<TEMP_PREFIX>"
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
DOWNLOAD_ONLY=<DOWNLOAD_ONLY>
source "$RELATIVE_DIR/functions" $@
