#!/bin/bash
#############
## Specifics
##
DEP=(modules pkg-config)
PACKAGE='libpng'

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.org/source_packages/<LIBPNG>.tar.gz'
EXTRACT='<LIBPNG>.tar.gz'
CONFIGURE="false"
BUILD='true'
INSTALL='true'

pre_run() {
    unset MODULEPATH
    source $PACKAGES_DIR/Modules/<MODULES>/init/bash
    module load moose-tools
    CONFIGURE="./configure --prefix=$PACKAGES_DIR/$PACKAGE --with-pkgconfigdir=$PKG_CONFIG_PATH"
}

post_run() {
    return
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
