#!/bin/bash
#############
## Specifics
##
DEP=(tcl moose_profile)
PACKAGE='modules'

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.inl.gov/source_packages/modules-<MODULES>.tar.gz'
EXTRACT='modules-<MODULES>.tar.gz'
CONFIGURE='false'
BUILD='true'
INSTALL='true'

pre_run() {
    if [ -d "$PACKAGES_DIR/Modules" ]; then
	rm -rf "$PACKAGES_DIR/Modules"
    fi
    if [ `uname` = "Darwin" ]; then
        CONFIGURE="./configure --prefix=$PACKAGES_DIR --with-tcl=$PACKAGES_DIR/<TCL>/lib"
    else
        CONFIGURE="CPPFLAGS=-DUSE_INTERP_ERRORLINE ./configure --prefix=$PACKAGES_DIR"
    fi
}
post_run() {
    mkdir -p "$PACKAGES_DIR/Modules/<MODULES>/adv_modules"
    mkdir -p "$PACKAGES_DIR/Modules/<MODULES>/openmpi_clang"
    mkdir -p "$PACKAGES_DIR/Modules/<MODULES>/openmpi_gcc"
    mkdir -p "$PACKAGES_DIR/Modules/<MODULES>/mpich_clang"
    mkdir -p "$PACKAGES_DIR/Modules/<MODULES>/mpich_gcc"
    mkdir -p "$PACKAGES_DIR/Modules/<MODULES>/civet"
    mkdir -p "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose"
    mkdir -p "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/civet"
    cat <<EOF > "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/civet/.civet"
#%Module1.0#####################################################################
##
## Civet support modules
##
##
set          BASE_PATH  "$PACKAGES_DIR"
prepend-path MODULEPATH "\$BASE_PATH/Modules/<MODULES>/civet"
EOF
    cat <<EOF > "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/advanced_modules"
#%Module1.0#####################################################################
##
## MOOSE extended modules
##
##
set          BASE_PATH  "$PACKAGES_DIR"
prepend-path MODULEPATH "\$BASE_PATH/Modules/<MODULES>/adv_modules"
EOF
    cat <<EOF > "$PACKAGES_DIR/Modules/<MODULES>/adv_modules/petsc-head"
#%Module1.0#####################################################################
##
## PETSC head (run $PACKAGES_DIR/build_PETSc-head to obtain/install latest PETSc) modulefile
##
##
##
proc ModulesHelp { } {
        puts stderr "\n\tThis is the PETSc head module. You must run:"
        puts stderr "\n\t\t/opt/moose/build_PETSc-head"
        puts stderr "\n\tThat script builds everything you need. You"
        puts stderr "\tonly need to run that script once, or as"
        puts stderr "\toften as you like (script downloads nightly"
        puts stderr "\tsnapshot).\n"
}

# If HOME is set, use that in an attempt to find petsc_head/petsc
if { [ info exists ::env(HOME) ] } {
  eval set [ array get env HOME ]
  if [ file isdirectory "\$HOME/petsc_head/petsc" ] {
    # Based on uname, we determine which compiler to use
    if { [uname sysname] == "Darwin"} {
      module load mpich-clang
    } else {
      module load mpich-gcc
    }
    setenv PETSC_DIR "\$HOME/petsc_head/petsc"
  } else {
      puts stderr "\n\tDirectory: \$HOME/petsc_head/petsc"
      puts stderr "\tnot detected. You must first run:"
      puts stderr "\n\t\t/opt/moose/build_PETSc-head"
      puts stderr "\n\tThat script builds everything you need. You"
      puts stderr "\tonly need to run that script once, or as"
      puts stderr "\toften as you like (script downloads nightly"
      puts stderr "\tsnapshot).\n"
      break
  }
}
EOF
    if [ `uname` = "Darwin" ]; then
        cat <<EOF > "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-tools"
#%Module1.0#####################################################################
##
## MOOSE Tools Module
##
##
##
set             BASE_PATH       "$PACKAGES_DIR"

# Binary PATH for supporting binaries
prepend-path    PKG_CONFIG_PATH "\$BASE_PATH/<PKG_CONFIG>/pkgconfig"
prepend-path    PATH            "\$BASE_PATH/<PKG_CONFIG>/bin"
prepend-path    PATH            "\$BASE_PATH/<GLIB>/bin"
prepend-path    PATH            "\$BASE_PATH/<DOXYGEN>/bin"
prepend-path    PATH            "\$BASE_PATH/<GRAPHVIZ>/bin"
prepend-path    PATH            "\$BASE_PATH/<LCOV>/usr/bin"
prepend-path    PATH            "\$BASE_PATH/<GNUPLOT>/bin"

# MAN Pages for Doxygen / Graphviz / Lcov / GNUPlot
prepend-path    MANPATH         "\$BASE_PATH/<DOXYGEN>/man"
prepend-path    MANPATH         "\$BASE_PATH/<GRAPHVIZ>/share/man"
prepend-path    MANPATH         "\$BASE_PATH/<LCOV>/usr/share/man"
prepend-path    MANPATH         "\$BASE_PATH/<GNUPLOT>/share/man"

# Load miniconda (enables Peacock)
module load miniconda

EOF
    else
        cat <<EOF > "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-tools"
#%Module1.0#####################################################################
##
## MOOSE Tools Module
##
##
##
set             BASE_PATH       "$PACKAGES_DIR"

# Binary PATH for supporting binaries
prepend-path    PATH            "\$BASE_PATH/<DOXYGEN>/bin"
prepend-path    PATH            "\$BASE_PATH/<GRAPHVIZ>/bin"
prepend-path    PATH            "\$BASE_PATH/<LCOV>/usr/bin"
prepend-path    PATH            "\$BASE_PATH/<GNUPLOT>/bin"

# MAN Pages for Doxygen / Graphviz / Lcov / GNUPlot
prepend-path    MANPATH         "\$BASE_PATH/<DOXYGEN>/man"
prepend-path    MANPATH         "\$BASE_PATH/<GRAPHVIZ>/share/man"
prepend-path    MANPATH         "\$BASE_PATH/<LCOV>/usr/share/man"
prepend-path    MANPATH         "\$BASE_PATH/<GNUPLOT>/share/man"

# Load miniconda (enables Peacock)
module load miniconda

EOF
    fi
    cat <<EOF > "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-dev-clang"
#%Module1.0#####################################################################
##
## Clang MOOSE DEV Module
##
##
##
conflict moose-dev-clang-alt moose-dev-gcc moose-dev-gcc-alt
module load moose/.<MPICH>_<CLANG>
module load moose/.<PETSC_DEFAULT>_<MPICH>_<CLANG>-opt
module load moose/.<TBB>
module load moose/.<CPPUNIT>_<CLANG>

# If MOOSE_DIR is set, help the user out by prepending the moose/python path
if { [ info exists ::env(MOOSE_DIR) ] } {
  eval set [ array get env MOOSE_DIR ]
  if [ file isdirectory "\$MOOSE_DIR/python" ] {
    prepend-path PYTHONPATH "\$MOOSE_DIR/python"
  }
}
EOF
    cat <<EOF > "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-dev-gcc"
#%Module1.0#####################################################################
##
## GCC MOOSE DEV Module
##
##
##
conflict moose-dev-gcc-alt moose-dev-clang moose-dev-clang-alt
module load moose/.<MPICH>_<GCC>
module load moose/.<PETSC_DEFAULT>_<MPICH>_<GCC>-opt
module load moose/.<TBB>
module load moose/.<CPPUNIT>_<GCC>

# If MOOSE_DIR is set, help the user out by prepending the moose/python path
if { [ info exists ::env(MOOSE_DIR) ] } {
  eval set [ array get env MOOSE_DIR ]
  if [ file isdirectory "\$MOOSE_DIR/python" ] {
    prepend-path PYTHONPATH "\$MOOSE_DIR/python"
  }
}
EOF
    cat <<EOF > "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-dev-clang-alt"
#%Module1.0#####################################################################
##
## Clang MOOSE DEV ALT Module
##
##
##
conflict moose-dev-clang moose-dev-gcc moose-dev-alt
module load moose/.<MPICH>_<CLANG>
module load moose/.<PETSC_ALT>_<MPICH>_<CLANG>-opt
module load moose/.<TBB>
module load moose/.<CPPUNIT>_<CLANG>

# If MOOSE_DIR is set, help the user out by prepending the moose/python path
if { [ info exists ::env(MOOSE_DIR) ] } {
  eval set [ array get env MOOSE_DIR ]
  if [ file isdirectory "\$MOOSE_DIR/python" ] {
    prepend-path PYTHONPATH "\$MOOSE_DIR/python"
  }
}
EOF
    cat <<EOF > "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-dev-gcc-alt"
#%Module1.0#####################################################################
##
## GCC MOOSE DEV ALT Module
##
##
##
conflict moose-dev-gcc moose-dev-clang moose-dev-clang-alt
module load moose/.<MPICH>_<GCC>
module load moose/.<PETSC_ALT>_<MPICH>_<GCC>-opt
module load moose/.<TBB>
module load moose/.<CPPUNIT>_<GCC>

# If MOOSE_DIR is set, help the user out by prepending the moose/python path
if { [ info exists ::env(MOOSE_DIR) ] } {
  eval set [ array get env MOOSE_DIR ]
  if [ file isdirectory "\$MOOSE_DIR/python" ] {
    prepend-path PYTHONPATH "\$MOOSE_DIR/python"
  }
}
EOF
    # Create .intel module so ccache works
    cd "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose"
    ln -s ../null .intel
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR="<PACKAGES_DIR>"
RELATIVE_DIR="<RELATIVE_DIR>"
DOWNLOAD_DIR="<DOWNLOAD_DIR>"
TEMP_PREFIX="<TEMP_PREFIX>"
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
DOWNLOAD_ONLY=<DOWNLOAD_ONLY>
source "$RELATIVE_DIR/functions" $@
