#!/bin/bash
#############
## Specifics
##
DEP=()
PACKAGE='moose_profile'
SERIAL=True

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='false'
EXTRACT='false'
CONFIGURE='false'
BUILD='false'
INSTALL='false'

pre_run() {
  return
}

post_run() {
    mkdir -p "$PACKAGES_DIR/environments"
    cat <<EOF > "$PACKAGES_DIR/environments/moose_profile"
#!/bin/bash
### Modules Source ###

# Silence the module system a bit
export MODULES_VERBOSITY=concise

if [ -n "\$MODULESHOME" ] && [ \$(echo \$MODULEPATH | grep -c <PACKAGES_DIR>/Modules) -le 0 ]; then
  export MODULEPATH="\$MODULEPATH:<PACKAGES_DIR>/Modules/<MODULES>/modulefiles"
else
  MY_SHELL=\`ps -o comm= \$\$ | sed -e 's/-//'\`
  if [ -f <PACKAGES_DIR>/Modules/init/\${MY_SHELL} ]; then
    if [ "\${MY_SHELL}" = "sh" ]; then
      . <PACKAGES_DIR>/Modules/init/sh
    else
      source <PACKAGES_DIR>/Modules/init/\${MY_SHELL}
    fi
    if [ "\${MY_SHELL}" = "bash" ]; then
      source <PACKAGES_DIR>/Modules/init/bash_completion
      # Load custom MOOSE command bash autocomplete rules
      source "<PACKAGES_DIR>/environments/autocomplete_moose"
    fi
  else
    printf "Your current shell is not supported by Modules.\nYou will not be able to load any modules.\n"
  fi
fi

# MOOSE_PPS_WIDTH
export MOOSE_PPS_WIDTH=180

# Source the autojump profile if requested:
if [ -n "\$MOOSE_JUMP" ]; then
  source "<PACKAGES_DIR>/environments/autojump_profile"
fi

# Set helpful environment variables and functions
if [ \`uname -s\` = 'Darwin' ]; then
  export MOOSE_JOBS=\`/usr/sbin/sysctl -n hw.ncpu\`

  #### ICECREAM Control
  if [ -f /Library/LaunchDaemons/com.moose.icecream.plist ]; then
    function icecream() {
      if [ "\$1" = "start" ]; then
        sudo launchctl load /Library/LaunchDaemons/com.moose.icecream.plist
      elif [ "\$1" = "stop" ]; then
        sudo launchctl unload /Library/LaunchDaemons/com.moose.icecream.plist
      fi
    }
  fi
else
  export MOOSE_JOBS=\`cat /proc/cpuinfo | grep processor | wc -l\`
fi
EOF
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR="<PACKAGES_DIR>"
RELATIVE_DIR="<RELATIVE_DIR>"
DOWNLOAD_DIR="<DOWNLOAD_DIR>"
TEMP_PREFIX="<TEMP_PREFIX>"
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
DOWNLOAD_ONLY=<DOWNLOAD_ONLY>
source "$RELATIVE_DIR/functions" $@
