#!/bin/bash
#############
## Specifics
##
DEP=(modules pkg-config miniconda)
PACKAGE='pcre'

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.org/source_packages/<PCRE>.tar.gz'
EXTRACT='<PCRE>.tar.gz'
CONFIGURE="./configure --prefix=$PACKAGES_DIR/$PACKAGE --enable-utf --enable-unicode-properties"
BUILD='true'
INSTALL='true'

pre_run() {
    if [ -d $PACKAGES_DIR/$PACKAGE ]; then
      rm -rf $PACKAGES_DIR/$PACKAGE
    fi
    unset MODULEPATH
    source $PACKAGES_DIR/Modules/<MODULES>/init/bash
    module load moose-tools
}

post_run() {
    cp $PACKAGES_DIR/$PACKAGE/lib/pkgconfig/* $PKG_CONFIG_PATH
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
