#!/bin/bash
#############
## Specifics
##
DEP=(modules cmake gcc llvm mpich-clang)
PACKAGE='<PETSC_ALT>-mpich-clang-dbg'

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.org/source_packages/<PETSC_ALT>.tar.gz'
EXTRACT='<PETSC_ALT>.tar.gz'
CONFIGURE="false"
BUILD='false'
INSTALL='false'

pre_run() {
    if [ -d $PACKAGES_DIR/petsc/mpich_<PETSC_ALT>/clang-dbg-superlu ]; then
	rm -rf $PACKAGES_DIR/petsc/mpich_<PETSC_ALT>/clang-dbg-superlu
    fi
    unset MODULEPATH
    source $PACKAGES_DIR/Modules/<MODULES>/init/bash
    module load advanced_modules cmake mpich-clang
    ./configure \
--prefix=$PACKAGES_DIR/petsc/mpich_<PETSC_ALT>/clang-dbg-superlu \
--download-hypre=1 \
--with-ssl=0 \
--with-debugging=1 \
--with-pic=1 \
--with-shared-libraries=1 \
--with-cc=mpicc \
--with-cxx=mpicxx \
--with-fc=mpif90 \
--download-metis=1 \
--download-parmetis=1 \
--download-fblaslapack=1 \
--download-superlu_dist=1 \
--download-mumps=1 \
--download-scalapack=1 \
-CC=mpicc -CXX=mpicxx -FC=mpif90 -F77=mpif77 -F90=mpif90 \
-CFLAGS='-fPIC -fopenmp' \
-CXXFLAGS='-fPIC -fopenmp' \
-FFLAGS='-fPIC -fopenmp' \
-FCFLAGS='-fPIC -fopenmp' \
-F90FLAGS='-fPIC -fopenmp' \
-F77FLAGS='-fPIC -fopenmp'
}

post_run() {
    if [ `uname` = "Darwin" ]; then
	make PETSC_DIR=$1/<PETSC_ALT> PETSC_ARCH=arch-darwin-c-debug all
	if [ $? -ne 0 ]; then echo 'Failed to build'; cleanup 1; fi
	make PETSC_DIR=$1/<PETSC_ALT> PETSC_ARCH=arch-darwin-c-debug install
	if [ $? -ne 0 ]; then echo 'Failed to install'; cleanup 1; fi
    else
	make PETSC_DIR=$1/<PETSC_ALT> PETSC_ARCH=arch-linux2-c-debug all
	if [ $? -ne 0 ]; then echo 'Failed to build'; cleanup 1; fi
	make PETSC_DIR=$1/<PETSC_ALT> PETSC_ARCH=arch-linux2-c-debug install
	if [ $? -ne 0 ]; then echo 'Failed to install'; cleanup 1; fi
    fi
    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose/.mpich_<PETSC_ALT>-clang-dbg
#%Module1.0#####################################################################
##
## MPICH Clang <PETSC_ALT> superlu Debug modulefile
##
##
##
set         BASE_PATH        $PACKAGES_DIR
setenv      PETSC_DIR        \$BASE_PATH/petsc/mpich_<PETSC_ALT>/clang-dbg-superlu
EOF
    cd $PACKAGES_DIR/Modules/<MODULES>/mpich_clang
    ln -s ../modulefiles/moose/.mpich_<PETSC_ALT>-clang-dbg <PETSC_ALT>-dbg

}

##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run `pwd`
# configure
# make
# make install
# post_run `pwd`
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
