#!/bin/bash
#############
## Specifics
##
DEP=(modules cmake gcc openmpi-gcc)
PACKAGE='<PETSC_NEW>-openmpi-gcc'

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.org/source_packages/<PETSC_NEW>.tar.gz'
EXTRACT='<PETSC_NEW>.tar.gz'
CONFIGURE="./configure \
--prefix=$PACKAGES_DIR/petsc/openmpi_<PETSC_NEW>/gcc-opt-superlu \
--download-hypre=1 \
--with-ssl=0 \
--with-debugging=no \
--with-pic=1 \
--with-shared-libraries=1 \
--with-cc=mpicc \
--with-cxx=mpicxx \
--with-fc=mpif90 \
--download-fblaslapack=1 \
--download-metis=1 \
--download-parmetis=1 \
--download-superlu_dist=1 \
--download-mumps=1 \
--download-scalapack=1 \
CC=mpicc CXX=mpicxx FC=mpif90 F77=mpif77 F90=mpif90 \
CFLAGS='-fPIC -fopenmp' \
CXXFLAGS='-fPIC -fopenmp' \
FFLAGS='-fPIC -fopenmp' \
FCFLAGS='-fPIC -fopenmp' \
F90FLAGS='-fPIC -fopenmp' \
F77FLAGS='-fPIC -fopenmp'"

BUILD='false'
INSTALL='false'

pre_run() {
    if [ -d $PACKAGES_DIR/petsc/openmpi_<PETSC_NEW>/gcc-opt-superlu ]; then
	rm -rf $PACKAGES_DIR/petsc/openmpi_<PETSC_NEW>/gcc-opt-superlu
    fi
    unset MODULEPATH
    source $PACKAGES_DIR/Modules/<MODULES>/init/bash
    module load advanced_modules cmake openmpi-gcc
}

post_run() {
    if [ `uname` = "Darwin" ]; then
	make PETSC_DIR=$1/<PETSC_NEW> PETSC_ARCH=arch-darwin-c-opt all
	if [ $? -ne 0 ]; then echo "Error while building PETSc"; cleanup 1; fi
	make PETSC_DIR=$1/<PETSC_NEW> PETSC_ARCH=arch-darwin-c-opt install
	if [ $? -ne 0 ]; then echo "Error while installing PETSc"; cleanup 1; fi
    else
	make PETSC_DIR=$1/<PETSC_NEW> PETSC_ARCH=arch-linux2-c-opt all
	if [ $? -ne 0 ]; then echo "Error while building PETSc"; cleanup 1; fi
	make PETSC_DIR=$1/<PETSC_NEW> PETSC_ARCH=arch-linux2-c-opt install
	if [ $? -ne 0 ]; then echo "Error while installing PETSc"; cleanup 1; fi
    fi
    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose/.openmpi_<PETSC_NEW>-gcc
#%Module1.0#####################################################################
##
## OpenMPI GCC <PETSC_NEW> superlu modulefile
##
##
##
set         BASE_PATH        $PACKAGES_DIR
setenv      PETSC_DIR        \$BASE_PATH/petsc/openmpi_<PETSC_NEW>/gcc-opt-superlu
EOF
    cd $PACKAGES_DIR/Modules/<MODULES>/openmpi_gcc
    ln -s ../modulefiles/moose/.openmpi_<PETSC_NEW>-gcc <PETSC_NEW>

    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/civet/openmpi-gcc-petsc_new-vtk-trilinos-opt
#%Module1.0#####################################################################
##
## Civet support module
## <PETSC_NEW>
## <GCC>
## <OPENMPI>
## <VTK>
## <TRILINOS>
##
module load moose/.<OPENMPI>_gcc
module load moose/.openmpi_<PETSC_NEW>-gcc
module load moose/.<VTK>-gcc
module load moose/.<TBB>
module load moose/.<CPPUNIT>-gcc
module load moose/.openmpi_<TRILINOS>-gcc-opt

EOF

    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/civet/openmpi-gcc-petsc_new-vtk-trilinos-dbg
#%Module1.0#####################################################################
##
## Civet support module
## <PETSC_NEW>
## <GCC>
## <OPENMPI>
## <VTK>
## <TRILINOS>
##
module load moose/.<OPENMPI>_gcc
module load moose/.openmpi_<PETSC_NEW>-gcc
module load moose/.<VTK>-gcc
module load moose/.<TBB>
module load moose/.<CPPUNIT>-gcc
module load moose/.openmpi_<TRILINOS>-gcc-dbg

EOF

    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/civet/openmpi-gcc-petsc_new-vtk
#%Module1.0#####################################################################
##
## Civet support module
## <PETSC_NEW>
## <GCC>
## <OPENMPI>
## <VTK>
##
module load moose/.<OPENMPI>_gcc
module load moose/.openmpi_<PETSC_NEW>-gcc
module load moose/.<VTK>-gcc
module load moose/.<TBB>
module load moose/.<CPPUNIT>-gcc

EOF

    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/civet/openmpi-gcc-petsc_new
#%Module1.0#####################################################################
##
## Civet support module
## <PETSC_NEW>
## <GCC>
## <OPENMPI>
##
module load moose/.<OPENMPI>_gcc
module load moose/.openmpi_<PETSC_NEW>-gcc
module load moose/.<VTK>-gcc
module load moose/.<CPPUNIT>-gcc

EOF
}

##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run `pwd`
# configure
# make
# make install
# post_run `pwd`
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
