#!/bin/bash
#############
## Specifics
##
DEP=(modules cmake gcc openmpi-gcc)
PACKAGE='<PETSC_ALT>-openmpi-gcc-dbg'
SERIAL=True

#####
# Set the operating system allowed to build this module
#
ARCH=(Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.org/source_packages/<PETSC_ALT>.tar.gz'
EXTRACT='<PETSC_ALT>.tar.gz'
CONFIGURE="false"
BUILD='false'
INSTALL='false'

clean_petsc() {
    if [ -d $PACKAGES_DIR/petsc/openmpi_<PETSC_ALT>/gcc-dbg-superlu ]; then
	rm -rf $PACKAGES_DIR/petsc/openmpi_<PETSC_ALT>/gcc-dbg-superlu
    fi
    clean_attempt
    extract
}

pre_run() {
    # Fix for darwin Fortran linking issue:
    if [ `uname` = "Darwin" ]; then
        cat <<EOF > petsc_darwin.patch
--- config/BuildSystem/config/libraries.py	2015-06-09 15:24:49.000000000 -0600
+++ config/BuildSystem/config/libraries.py	2017-10-25 16:40:07.000000000 -0600
@@ -50,7 +50,7 @@
         flagName  = self.language[-1]+'SharedLinkerFlag'
         flagSubst = self.language[-1].upper()+'_LINKER_SLFLAG'
         dirname   = os.path.dirname(library).replace('\\ ',' ').replace(' ', '\\ ').replace('\\(','(').replace('(', '\\(').replace('\\)',')').replace(')', '\\)')
-        if hasattr(self.setCompilers, flagName) and not getattr(self.setCompilers, flagName) is None:
+        if False:
           return [getattr(self.setCompilers, flagName)+dirname,'-L'+dirname,'-l'+name]
         if flagSubst in self.argDB:
           return [self.argDB[flagSubst]+dirname,'-L'+dirname,'-l'+name]

EOF
        patch -p0 < petsc_darwin.patch
    fi

    unset MODULEPATH
    source $PACKAGES_DIR/Modules/<MODULES>/init/bash
    module load advanced_modules cmake openmpi-gcc
    CONFIGURE="./configure \
--prefix=$PACKAGES_DIR/petsc/openmpi_<PETSC_ALT>/gcc-dbg-superlu \
--download-hypre=1 \
--with-ssl=0 \
--with-debugging=1 \
--with-pic=1 \
--with-shared-libraries=1 \
--with-cc=mpicc \
--with-cxx=mpicxx \
--with-fc=mpif90 \
--download-metis=1 \
--download-parmetis=1 \
--download-fblaslapack=1 \
--download-superlu_dist=1 \
--download-mumps=1 \
--download-scalapack=1 \
-CC=mpicc -CXX=mpicxx -FC=mpif90 -F77=mpif77 -F90=mpif90 \
-CFLAGS='-fPIC -fopenmp' \
-CXXFLAGS='-fPIC -fopenmp' \
-FFLAGS='-fPIC -fopenmp' \
-FCFLAGS='-fPIC -fopenmp' \
-F90FLAGS='-fPIC -fopenmp' \
-F77FLAGS='-fPIC -fopenmp'"

    if [ `uname` = "Darwin" ]; then
	try_command 3 "clean_petsc; configure; make MAKE_NP=1 PETSC_DIR=$1/<PETSC_ALT> PETSC_ARCH=arch-darwin-c-debug all; make PETSC_DIR=$1/<PETSC_ALT> PETSC_ARCH=arch-darwin-c-debug install"
    else
	try_command 3 "clean_petsc; configure; make MAKE_NP=1 PETSC_DIR=$1/<PETSC_ALT> PETSC_ARCH=arch-linux2-c-debug all; make PETSC_DIR=$1/<PETSC_ALT> PETSC_ARCH=arch-linux2-c-debug install"
    fi
    # So we do not run configure a second time
    CONFIGURE="false"
}

post_run() {
    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose/.openmpi_<PETSC_ALT>_dbg-gcc
#%Module1.0#####################################################################
##
## OpenMPI GCC <PETSC_ALT> debug superlu modulefile
##
##
##
set         BASE_PATH        $PACKAGES_DIR
setenv      PETSC_DIR        \$BASE_PATH/petsc/openmpi_<PETSC_ALT>/gcc-dbg-superlu
EOF
    cd $PACKAGES_DIR/Modules/<MODULES>/openmpi_gcc
    ln -s ../modulefiles/moose/.openmpi_<PETSC_ALT>_dbg-gcc <PETSC_ALT>-dbg

}

##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run `pwd`
# configure
# make
# make install
# post_run `pwd`
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
