#!/bin/bash
#############
## Specifics
##
DEP=(modules cmake gcc mpich-gcc)
PACKAGE='<PETSC_ALT>-mpich-gcc-opt'

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.org/source_packages/<PETSC_ALT>.tar.gz'
EXTRACT='<PETSC_ALT>.tar.gz'
CONFIGURE="false"
BUILD='false'
INSTALL='false'

clean_petsc() {
    if [ -d $PACKAGES_DIR/petsc/mpich_<PETSC_ALT>/gcc-opt-superlu ]; then
	rm -rf $PACKAGES_DIR/petsc/mpich_<PETSC_ALT>/gcc-opt-superlu
    fi
    clean_attempt
    extract
}

pre_run() {
    unset MODULEPATH
    source $PACKAGES_DIR/Modules/<MODULES>/init/bash
    module load advanced_modules cmake mpich-gcc
    CONFIGURE="./configure \
--prefix=$PACKAGES_DIR/petsc/mpich_<PETSC_ALT>/gcc-opt-superlu \
--download-hypre=1 \
--with-ssl=0 \
--with-debugging=no \
--with-pic=1 \
--with-shared-libraries=1 \
--with-cc=mpicc \
--with-cxx=mpicxx \
--with-fc=mpif90 \
--download-metis=1 \
--download-parmetis=1 \
--download-fblaslapack=1 \
--download-superlu_dist=1 \
--download-mumps=1 \
--download-scalapack=1 \
-CC=mpicc -CXX=mpicxx -FC=mpif90 -F77=mpif77 -F90=mpif90 \
-CFLAGS='-fPIC -fopenmp' \
-CXXFLAGS='-fPIC -fopenmp' \
-FFLAGS='-fPIC -fopenmp' \
-FCFLAGS='-fPIC -fopenmp' \
-F90FLAGS='-fPIC -fopenmp' \
-F77FLAGS='-fPIC -fopenmp'"

    if [ `uname` = "Darwin" ]; then
	try_command 3 "clean_petsc; configure; make MAKE_NP=1 PETSC_DIR=$1/<PETSC_ALT> PETSC_ARCH=arch-darwin-c-opt all; make PETSC_DIR=$1/<PETSC_ALT> PETSC_ARCH=arch-darwin-c-opt install"
    else
	try_command 3 "clean_petsc; configure; make MAKE_NP=1 PETSC_DIR=$1/<PETSC_ALT> PETSC_ARCH=arch-linux2-c-opt all; make PETSC_DIR=$1/<PETSC_ALT> PETSC_ARCH=arch-linux2-c-opt install"
    fi
    # So we do not run configure a second time
    CONFIGURE="false"
}

post_run() {
    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose/.mpich_<PETSC_ALT>_opt-gcc
#%Module1.0#####################################################################
##
## MPICH GCC <PETSC_ALT> optimized superlu modulefile
##
##
##
set         BASE_PATH        $PACKAGES_DIR
setenv      PETSC_DIR        \$BASE_PATH/petsc/mpich_<PETSC_ALT>/gcc-opt-superlu
EOF

    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/civet/mpich-gcc-petsc_alt-vtk-trilinos-opt
#%Module1.0#####################################################################
##
## Civet support module
## <PETSC_ALT>
## <GCC>
## <MPICH>
## <VTK>
## <TRILINOS>
##
module load moose/.<MPICH>_gcc
module load moose/.mpich_<PETSC_ALT>_opt-gcc
module load moose/.<VTK>-gcc
module load moose/.<TBB>
module load moose/.<CPPUNIT>-gcc
module load moose/.mpich_<TRILINOS>-gcc-opt
module load ccache
module load moose-tools

EOF

    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/civet/mpich-gcc-petsc_alt-vtk-trilinos-dbg
#%Module1.0#####################################################################
##
## Civet support module
## <PETSC_ALT>
## <GCC>
## <MPICH>
## <VTK>
## <TRILINOS>
##
module load moose/.<MPICH>_gcc
module load moose/.mpich_<PETSC_ALT>_opt-gcc
module load moose/.<VTK>-gcc
module load moose/.<TBB>
module load moose/.<CPPUNIT>-gcc
module load moose/.mpich_<TRILINOS>-gcc-dbg
module load ccache
module load moose-tools

EOF

    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/civet/mpich-gcc-petsc_alt-trilinos-opt
#%Module1.0#####################################################################
##
## Civet support module
## <PETSC_ALT>
## <GCC>
## <MPICH>
## <TRILINOS>
##
module load moose/.<MPICH>_gcc
module load moose/.mpich_<PETSC_ALT>_opt-gcc
module load moose/.<TBB>
module load moose/.<CPPUNIT>-gcc
module load moose/.mpich_<TRILINOS>-gcc-opt
module load ccache
module load moose-tools

EOF

    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/civet/mpich-gcc-petsc_alt-trilinos-dbg
#%Module1.0#####################################################################
##
## Civet support module
## <PETSC_ALT>
## <GCC>
## <MPICH>
## <TRILINOS>
##
module load moose/.<MPICH>_gcc
module load moose/.mpich_<PETSC_ALT>_opt-gcc
module load moose/.<TBB>
module load moose/.<CPPUNIT>-gcc
module load moose/.mpich_<TRILINOS>-gcc-dbg
module load ccache
module load moose-tools

EOF

    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/civet/mpich-gcc-petsc_alt-vtk
#%Module1.0#####################################################################
##
## Civet support module
## <PETSC_ALT>
## <GCC>
## <MPICH>
## <VTK>
##
module load moose/.<MPICH>_gcc
module load moose/.mpich_<PETSC_ALT>_opt-gcc
module load moose/.<VTK>-gcc
module load moose/.<TBB>
module load moose/.<CPPUNIT>-gcc
module load ccache
module load moose-tools

EOF

    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/civet/mpich-gcc-petsc_alt_opt
#%Module1.0#####################################################################
##
## Civet support module
## <PETSC_ALT>
## <GCC>
## <MPICH>
##
module load moose/.<MPICH>_gcc
module load moose/.mpich_<PETSC_ALT>_opt-gcc
module load moose/.<TBB>
module load moose/.<CPPUNIT>-gcc
module load ccache
module load moose-tools

EOF

    cd $PACKAGES_DIR/Modules/<MODULES>/mpich_gcc
    ln -s ../modulefiles/moose/.mpich_<PETSC_ALT>_opt-gcc <PETSC_ALT>

}

##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run `pwd`
# configure
# make
# make install
# post_run `pwd`
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
