#!/bin/bash
#############
## Specifics
##
DEP=(miniconda miniconda-old)
PACKAGE='pip-installs'

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='false'
EXTRACT='false'
CONFIGURE="false"
BUILD='false'
INSTALL='false'

pre_run() {
    cd $1
    unset MODULEPATH
    source $PACKAGES_DIR/Modules/<MODULES>/init/bash
    condas=(miniconda miniconda-old)
    for which_conda in ${condas[*]}; do
	module purge
	module load advanced_modules $which_conda
	pip install --no-cache-dir markdown python-markdown-math pybtex bs4 jinja2 livereload daemonlite pylint==1.6.5 lxml pylatexenc anytree
	if [ $? -ne 0 ]; then echo "Failed to install dependency packages for $PACKAGE"; cleanup 1; fi
    done
}
post_run() {
    return
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
