#!/bin/bash
#############
## Specifics
##
DEP=(modules)
PACKAGE="<PKG_CONFIG>"

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.inl.gov/source_packages/<PKG_CONFIG>.tar.gz'
EXTRACT='<PKG_CONFIG>.tar.gz'
CONFIGURE='false'
BUILD='true'
INSTALL='true'

pre_run() {
    CONFIGURE="./configure --prefix=$PACKAGES_DIR/<PKG_CONFIG> --with-internal-glib"
}

post_run() {
    mkdir -p "$PACKAGES_DIR/<PKG_CONFIG>/pkgconfig"

    # Remove previous module section
    sed -i'' -e '/#PKGCONFIG/,/#ENDPKGCONFIG/d' "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-tools"
    # Append new paths to moose-tools module
    cat <<EOF >> "$PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose-tools"
#PKGCONFIG
prepend-path    PKG_CONFIG_PATH "\$BASE_PATH/<PKG_CONFIG>/pkgconfig"
prepend-path    PATH            "\$BASE_PATH/<PKG_CONFIG>/bin"
#ENDPKGCONFIG
EOF
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
PACKAGES_DIR="<PACKAGES_DIR>"
RELATIVE_DIR="<RELATIVE_DIR>"
DOWNLOAD_DIR="<DOWNLOAD_DIR>"
TEMP_PREFIX="<TEMP_PREFIX>"
MOOSE_JOBS=<MOOSE_JOBS>
KEEP_FAILED=<KEEP_FAILED>
DOWNLOAD_ONLY=<DOWNLOAD_ONLY>
source "$RELATIVE_DIR/functions" $@
