#!/bin/bash
#############
## Specifics
##
DEP=(modules glib pango)
PACKAGE='qt5'

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.org/source_packages/<QT5>.tar.gz'
EXTRACT='<QT5>.tar.gz'
CONFIGURE='false'
BUILD='true'
INSTALL='true'

pre_run() {
    if [ -d $PACKAGES_DIR/$PACKAGE ]; then
	rm -rf $PACKAGES_DIR/$PACKAGE
    fi
    unset MODULEPATH
    source $PACKAGES_DIR/Modules/<MODULES>/init/bash
    module load moose-tools
    CONFIGURE="CCPFLAGS='-I/opt/X11/include' ./configure --prefix=$PACKAGES_DIR/$PACKAGE --with-x=no --with-qt=no --with-tcl=no --with-tdl=no"
}
post_run() {
    return
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
