#!/bin/bash
#############
## Specifics
##
DEP=(modules gcc cmake)
PACKAGE='seacas'

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='false'
EXTRACT='false'
CONFIGURE="false"
BUILD='false'
INSTALL='false'

pre_run() {
    cd $PACKAGES_DIR
    if [ -d seacas ]; then rm -rf seacas; fi
    git clone https://github.com/milljm/seacas.git
    if [ $? -ne 0 ]; then echo "Failed to clone SEACAS github repo"; cleanup 1; fi
    cd seacas
    git checkout jasons_installer
    cd contrib
    export ACCESS=$PACKAGES_DIR/seacas
    ./download_and_configure_prereqs.sh
    if [ $? -ne 0 ]; then echo "Failed to build SEACAS"; cleanup 1; fi
}
post_run() {
    return
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
