#!/bin/bash
#############
## Specifics
##
DEP=(modules cmake gcc llvm mpich-clang)
PACKAGE='trilinos-mpich-clang-dbg'

#####
# Set the operating system allowed to build this module
#
ARCH=(Darwin Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.org/source_packages/<TRILINOS>.tar.gz'
EXTRACT='<TRILINOS>.tar.gz'
CONFIGURE="
cmake \
-D CMAKE_INSTALL_PREFIX:PATH=$PACKAGES_DIR/<TRILINOS>/mpich-clang-dbg \
-D CMAKE_INSTALL_NAME_DIR:STRING=$PACKAGES_DIR/<TRILINOS>/mpich-clang-dbg/lib \
-D CMAKE_BUILD_TYPE:STRING=DEBUG \
-D BUILD_SHARED_LIBS=ON \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=OFF \
-D TPL_ENABLE_MPI:BOOL=ON \
-D TPL_ENABLE_MOAB=OFF \
-D TPL_ENABLE_BoostLib=OFF \
-D Trilinos_ENABLE_Ifpack=ON \
-D Trilinos_ENABLE_Ifpack2=ON \
-D Trilinos_ENABLE_Teuchos=ON \
-D Trilinos_ENABLE_ML=ON \
-D Trilinos_ENABLE_NOX=ON \
-D Trilinos_ENABLE_AztecOO=ON \
-D Trilinos_ENABLE_Epetra=ON \
-D Trilinos_ENABLE_EpetraExt=ON \
-D TPL_ENABLE_Libmesh=OFF \
-D MPI_BASE_DIR:PATH=$MPI_HOME \
-D Trilinos_ENABLE_CXX11:BOOL=ON \
-D Trilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
-D Trilinos_ASSERT_MISSING_PACKAGES=OFF \
-D Trilinos_EXTRA_REPOSITORIES=DataTransferKit \
-D DataTransferKit_FIND_DTK_DATA_DIR=../DataTransferKit \
-D Trilinos_ENABLE_DataTransferKit:BOOL=ON \
-D DataTransferKit_ENABLE_DBC:BOOL=ON \
-D DataTransferKit_ENABLE_TESTS:BOOL=ON \
-D DataTransferKit_ENABLE_EXAMPLES:BOOL=ON \
-D CMAKE_Fortran_FLAGS_DEBUG_OVERRIDE=-fPIC \
-D CMAKE_C_FLAGS_DEBUG_OVERRIDE=-fPIC \
-D CMAKE_CXX_FLAGS_DEBUG_OVERRIDE=-fPIC \
..
"
BUILD='true'
INSTALL='true'

pre_run() {
    if [ -d $PACKAGES_DIR/<TRILINOS>/mpich-clang-dbg ]; then
	rm -rf $PACKAGES_DIR/<TRILINOS>/mpich-clang-dbg
    fi
    unset MODULEPATH
    source $PACKAGES_DIR/Modules/<MODULES>/init/bash
    module load advanced_modules cmake mpich-clang
    git clone https://github.com/ORNL-CEES/DataTransferKit.git
    cd DataTransferKit
    git checkout <DTK>
    cd ../
    mkdir clang-dbg; cd clang-dbg
}

post_run() {
    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose/.mpich_<TRILINOS>-clang-dbg
#%Module1.0#####################################################################
##
##  Trilinos MPICH Clang Debug Module 
##
##
##
set          BASE_PATH          $PACKAGES_DIR

if { [uname sysname] != "Darwin" } {
  prepend-path         LD_LIBRARY_PATH     \$BASE_PATH/<TRILINOS>/mpich-clang-dbg/lib
}

setenv       TRILINOS_DIR                \$BASE_PATH/<TRILINOS>/mpich-clang-dbg
EOF
    cd $PACKAGES_DIR/Modules/3.2.10/mpich_clang
    ln -s ../modulefiles/moose/.mpich_<TRILINOS>-clang-dbg trilinos-dbg
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
