#!/bin/bash
#############
## Specifics
##
DEP=(modules cmake gcc)
PACKAGE='vtk-gcc'

#####
# Set the operating system allowed to build this module
#
ARCH=(Linux)

#####
# Setting any of these variables to 'false' effectively skips that step
# This is useful for items like 'autojump' which requires a git clone/checkout
DOWNLOAD='http://mooseframework.org/source_packages/<VTK>.tar.gz'
EXTRACT='<VTK>.tar.gz'
CONFIGURE="cmake ../<VTK> -DCMAKE_INSTALL_PREFIX=$PACKAGES_DIR/<VTK>/gcc-opt -DCMAKE_INSTALL_RPATH:STRING=$PACKAGES_DIR/<VTK>/gcc-opt/lib -DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON -DCMAKE_INSTALL_NAME_DIR:STRING=$PACKAGES_DIR/<VTK>/gcc-opt/lib -DCMAKE_MACOSX_RPATH:BOOL=ON -DVTK_WRAP_PYTHON=ON -Wno-dev"
BUILD='true'
INSTALL='true'

pre_run() {
    if [ -d $PACKAGES_DIR/<VTK>/gcc-opt ]; then
	rm -rf $PACKAGES_DIR/<VTK>/gcc-opt
    fi
    unset MODULEPATH
    source $PACKAGES_DIR/Modules/<MODULES>/init/bash
    module load advanced_modules cmake gcc
    export CC=gcc; export CXX=g++
    cat << 'EOF' > vtk_gcc.patch
diff -ur a/CMake/GenerateExportHeader.cmake b/CMake/GenerateExportHeader.cmake
--- a/CMake/GenerateExportHeader.cmake	2016-01-28 09:17:38.000000000 -0700
+++ b/CMake/GenerateExportHeader.cmake	2016-11-01 08:12:00.039505665 -0600
@@ -166,7 +166,7 @@
     execute_process(COMMAND ${CMAKE_C_COMPILER} ARGS --version
       OUTPUT_VARIABLE _gcc_version_info
       ERROR_VARIABLE _gcc_version_info)
-    string(REGEX MATCH "[345]\\.[0-9]\\.[0-9]*"
+    string(REGEX MATCH "[3456]\\.[0-9]\\.[0-9]*"
       _gcc_version "${_gcc_version_info}")
     # gcc on mac just reports: "gcc (GCC) 3.3 20030304 ..." without the
     # patch level, handle this here:
diff -ur a/CMake/vtkCompilerExtras.cmake b/CMake/vtkCompilerExtras.cmake
--- a/CMake/vtkCompilerExtras.cmake	2016-01-28 09:17:38.000000000 -0700
+++ b/CMake/vtkCompilerExtras.cmake	2016-11-01 08:11:27.091657847 -0600
@@ -32,7 +32,7 @@
     OUTPUT_VARIABLE _gcc_version_info
     ERROR_VARIABLE _gcc_version_info)
 
-  string (REGEX MATCH "[345]\\.[0-9]\\.[0-9]*"
+  string (REGEX MATCH "[3456]\\.[0-9]\\.[0-9]*"
     _gcc_version "${_gcc_version_info}")
   if(NOT _gcc_version)
     string (REGEX REPLACE ".*\\(GCC\\).*([34]\\.[0-9]).*" "\\1.0"
EOF
    patch -p1 < vtk_gcc.patch
    mkdir ../vtk-build; cd ../vtk-build
}

post_run() {
    cat <<EOF > $PACKAGES_DIR/Modules/<MODULES>/modulefiles/moose/.<VTK>-gcc
#%Module1.0#####################################################################
##
## <VTK> GCC Module
##
##
##
set             BASE_PATH          $PACKAGES_DIR

if { [uname sysname] != "Darwin" } {
  prepend-path    LD_LIBRARY_PATH    \$BASE_PATH/<VTK>/gcc-opt/lib
}

setenv          VTKINCLUDE_DIR                \$BASE_PATH/<VTK>/gcc-opt/include/<VTK_INCLUDE>
prepend-path    INCLUDE_PATH                  \$BASE_PATH/<VTK>/gcc-opt/include/<VTK_INCLUDE>
setenv          VTKLIB_DIR                    \$BASE_PATH/<VTK>/gcc-opt/lib
setenv          VTK6_PYTHON_DIR               \$BASE_PATH/<VTK>/gcc-opt/lib/python2.7/site-packages
EOF
    unset CC CXX
    cd $PACKAGES_DIR/Modules/<MODULES>/adv_modules
    if [ -f vtk-gcc ]; then rm -f vtk-gcc; fi
    ln -s ../modulefiles/moose/.<VTK>-gcc vtk-gcc
}
##
## End Specifics
##############
## The following script contains all the common functions.
## Those functions are executed in the following order:

# download
# extract
# pre-run
# configure
# make
# make install
# post_run
# cleanup

## pre_run and post_run are the only true specifics that are different
## with every package
source $RELATIVE_DIR/functions
